name: Deploy the NDI website

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute deployment on VPS
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/shared/workspace/ndi
            git fetch
            git reset --hard origin/main
            sudo /usr/bin/docker compose -f /opt/shared/workspace/ndi/compose.yaml up --build -d
